[platformio]
src_dir = .
data_dir = data

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs

# Configure Board Memory (OPI PSRAM is standard for ESP32-S3-WROOM-1)
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1

# Specify the custom partition table to allow large SPIFFS storage
board_build.partitions = partitions.csv

# Automatically manage libraries
lib_deps =
    olikraus/U8g2@^2.35.19

# Upload and Monitor options
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
